CREATE TABLE styles
(
style_id mediumint unsigned NOT NULL auto_increment,
style_name varchar(255) NOT NULL,
style_category varchar(255) NOT NULL,
style_version tinyint unsigned NOT NULL default 1,
style_category_number varchar(255) NOT NULL,
style_style_letter varchar(255) NOT NULL,
style_style_guide varchar(255) NOT NULL,
style_type enum('Lager', 'Ale', 'Mead', 'Wheat', 'Mixed', 'Cider'),
style_og_min float,
style_og_max float,
style_fg_min float,
style_fg_max float,
style_ibu_min float,
style_ibu_max float,
style_color_min float,
style_color_max float,
style_carb_min float,
style_carb_max float,
style_abv_min float,
style_abv_max float,
style_notes varchar(255),
style_profile varchar(255),
style_ingredients varchar(255),
style_examples varchar(255),
PRIMARY KEY (style_id),
INDEX (style_name),
INDEX (style_category),
INDEX (style_category_number),
INDEX (style_style_letter),
INDEX (style_type)
) AUTO_INCREMENT=50001;
